backend:
  name: git-gateway
  branch: main
  site_domain: lucky-madeleine-fc4893.netlify.app

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Post del Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha de publicación", name: "date", widget: "datetime", date_format: "DD/MM/YYYY", time_format: false }
      - { label: "Cuerpo del post", name: "body", widget: "markdown" }
